# Generated by Django 4.2.6 on 2023-11-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_itinerary_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
