# Generated by Django 4.2.7 on 2023-11-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_location_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='location',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
