# Generated by Django 4.2.7 on 2023-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='hotel',
            field=models.CharField(max_length=100),
        ),
    ]
