# Generated by Django 4.2.7 on 2023-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_itinerary_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='hotel',
            field=models.CharField(max_length=250),
        ),
    ]
