# Generated by Django 4.2.7 on 2023-11-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_rename_date_itinerary_hotel_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='places',
            new_name='place_list',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='hotel_list',
            field=models.TextField(),
        ),
    ]
