# Generated by Django 4.2.7 on 2023-11-14 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_rename_places_location_place_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='time',
        ),
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='search_keyword',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='time_slot',
            field=models.CharField(choices=[(1, 'Breakfast'), (2, 'Mid-Day Activity'), (3, 'Lunch'), (4, 'Evening Activity'), (5, 'Dinner')], max_length=50),
        ),
    ]
