# Generated by Django 4.2.7 on 2023-11-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_location_time_location_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
