# Generated by Django 4.2.7 on 2023-11-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_location_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='search_keyword',
            field=models.CharField(default='', max_length=150),
        ),
    ]
